group: travis_lts
env:
  global:
    TERM=dumb
language: node_js
node_js:
- 6
- 7
- 8
- 9
- lts/*
install: true
before_script:
- sudo apt update -y || true
- sudo apt install --no-install-recommends -y curl
- curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
- echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
- sudo apt update -y || true
- export CHROME_BIN=/usr/bin/google-chrome
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sudo apt install -y yarn libappindicator1 fonts-liberation
- wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
- sudo dpkg -i google-chrome*.deb || true
script:
- export root=$(pwd)
- >
  for project in \
    computed \
    observable \
    starter \
  ; do
    cd ${root}/${project}
    yarn -i
    yarn build
    yarn preghpages
  done
cache:
  directories:
  - $HOME/.npm
  - $HOME/.nvm
  - node_modules
